### ISSUE TITLE
rstats installation failing

### ISSUE THREAD

**Issue by ravianarase** [Planeshifter/node-Rstats#14]
node version-v5.2.0
npm version- 3.5.2
Error-
npm ERR! Linux 3.19.0-37-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! rstats@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rstats@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rstats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rstats
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rstats
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ravindra/RAVI/PROJECT/ECG/npm-debug.log

**Comment by voxnonecho** [comment]
Same. Here's my output:

```
npm ERR! node v5.4.0                                                                                                                                                                                                                      
npm ERR! npm  v3.3.12                                                                                                                                                                                                                     
npm ERR! code ELIFECYCLE                                                                                                                                                                                                                  
                                                                                                                                                                                                                                          
npm ERR! rstats@0.3.1 install: `node-gyp rebuild`                                                                                                                                                                                         
npm ERR! Exit status 1                                                                                                                                                                                                                    
npm ERR!                                                                                                                                                                                                                                  
npm ERR! Failed at the rstats@0.3.1 install script 'node-gyp rebuild'.                                                                                                                                                                    
npm ERR! Make sure you have the latest version of node.js and npm installed.                                                                                                                                                              
npm ERR! If you do, this is most likely a problem with the rstats package,                                                                                                                                                                
npm ERR! not with npm itself.                                                                                                                                                                                                             
npm ERR! Tell the author that this fails on your system:                                                                                                                                                                                  
npm ERR!     node-gyp rebuild                                                                                                                                                                                                             
npm ERR! You can get their info via:                                                                                                                                                                                                      
npm ERR!     npm owner ls rstats                                                                                                                                                                                                          
npm ERR! There is likely additional logging output above.                                                                                                                                                                                 
                                                                                                                                                                                                                                          
npm ERR! Please include the following file with any support request:                                                                                                                                                                      
npm ERR!     /home/elm/npm-debug.log```

**Comment by erickramer** [comment]
Failed for me too. Same error.

**Comment by Planeshifter** [comment]
The root of this issue is that the current version of the package on npm does not support node versions 4.0.0 and upwards due to breaking changes in the `nan` package. I am working on updating the package and except to have a new version on npm by the end of this week. For now, you might want to check out this fork https://github.com/ijsf/node-Rstats/tree/0918c18a9b6a865aced557ce2d9c1d26ea155126 by *ijsf*, who was so kind to update the package so that it works with current node versions.

**Comment by ravianarase** [comment]
thanks solved problem!

**Comment by philcontrolf1** [comment]
Has this issue been resolved? I'm still seeing the same issue as @ravianarase was seeing in January (probably because I'm still seeing v0.3.1).

**Comment by chrislarsenqlik** [comment]
So is current status that it is not usable on the current version of node? Latest I am seeing is 7mos ago. Thanks

**Comment by philcontrolf1** [comment]
I can't get it to work. But I'm not a node guru.

**Comment by petegordon** [comment]
Hi Sorry for the double post just posted this to the open issue [#16](https://github.com/Planeshifter/node-Rstats/issues/16) also.

Hi everyone! I am so very close to having it fully working with the latest versions of NodeJS. In fact it does work; but there seems to be a last problem with running cat or print causing a segmentation fault; but other calls work fine even writeFiles. You can install the npm module from github; and it will automatically clone and build RInside using npm package.json preinstall as a new package called RInsideNodeJS; from this repo fork... https://github.com/ColumbusCollaboratory/rinside) because the RINSIDE_CALLBACKS flag needed to be defined for NAN to work apparently. Try it by simply running this...

npm install https://github.com/ColumbusCollaboratory/node-Rstats

I'll pick up working on it next week; to try to find the segmentation fault problem which is apparently output stream related (anything that uses standard out in R--maybe the problem area). (fyi; I also changed it to use JSONLITE instead of RJSON).

**Comment by sempervalor** [comment]
Hey,

I have tried npm install rstats and I can't get pass this:

npm ERR! Linux 4.8.6-x86_64-linode78
npm ERR! argv "/root/.nvm/v4.6.2/bin/node" "/root/.nvm/v4.6.2/bin/npm" "install" "rstats"
npm ERR! node v4.6.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! rstats@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rstats@0.3.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the rstats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rstats
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls rstats
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/re3Node/npm-debug.log

I have tried "node-gyp rebuild' but I also get errors:

gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/4.6.2',
gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/v4.6.2/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/re3Node',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /root/re3Node) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/v4.6.2/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.8.6-x86_64-linode78
gyp ERR! command "/root/.nvm/v4.6.2/bin/node" "/root/.nvm/v4.6.2/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/re3Node
gyp ERR! node -v v4.6.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

Please advise.

Attached is the Debug file.
[npm-debug.txt](https://github.com/Planeshifter/node-Rstats/files/651721/npm-debug.txt)
